name: RuleBookPlugin
main: net.kunmc.lab.rulebookplugin.RuleBookPlugin
api-version: 1.15
version: 2.9.1
commands:
  rulebook:
    description: '/rulebook helpから見てね'
    usage: '/rulebook help から見てね'
    default: true
